# Generated by Django 4.2.1 on 2023-05-17 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_product_wb_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('image', models.ImageField(upload_to='media/partners', verbose_name='Логотип')),
                ('link', models.URLField(null=True, verbose_name='Ссылка на сайт партнера')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Банер', 'verbose_name_plural': 'Банеры'},
        ),
        migrations.AddField(
            model_name='banner',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Показывать на главной'),
        ),
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='banner',
            name='link',
            field=models.URLField(null=True, verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.color', verbose_name='Цвет'),
        ),
    ]
