# Generated by Django 4.2.1 on 2023-05-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_partner_alter_banner_options_banner_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='button_name',
            field=models.CharField(default='Подробнее', max_length=20, verbose_name='Название кнопки'),
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Виден в рекомендуемых'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Псевдоним'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Псевдоним'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Псевдоним'),
        ),
    ]
